export const MenuActionTypes = {
    FETCH_CURRENT_MENU_START: 'FETCH_CURRENT_MENU_START',
    FETCH_CURRENT_MENU_SUCCESS: 'FETCH_CURRENT_MENU_SUCCESS',
    FETCH_CURRENT_MENU_FAILURE: 'FETCH_CURRENT_MENU_FAILURE',
    SET_CURRENT_MENU_OPTIONS: 'SET_CURRENT_MENU_OPTIONS'
};
export const PendingActionTypes ={
    SHOW_LOADER_START:'SHOW_LOADER_START',
    SHOW_LOADER_CANCEL:'SHOW_LOADER_START' 
}

export default MenuActionTypes;